language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.6"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "ArduinoJson:5.13.2"
  - wget https://github.com/gioblu/PJON/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - sudo mv PJON-master $HOME/Arduino/libraries/PJON
script:
  - build_platform [uno]
  - build_platform nano
notifications:
  email:
    on_success: change
    on_failure: change